### ISSUE TITLE
Http Buffer Filter buffers GRPC streaming requests indefinitely

### ISSUE THREAD

**Issue by negator** [lyft/envoy#1053] opened 2017-06-06 03:06 UTC
This may be intended behavior, but enabling the http [buffer filter](https://lyft.github.io/envoy/docs/configuration/http_filters/buffer_filter.html?highlight=buffer#) (type = "decoder") appears to buffer grpc streaming requests until of an END_STREAM data frame is sent. This can be seen in the access log (after the client closes the connection due to timeout), which shows that a backend was not selected. Disabling the filter correctly routes to the backend without issue. 

This is fine for non-streaming grpc requests, however fails in the context of a persistent bidrectional grpc streaming session. Ideally, the filter would be disabled in context of a streaming rpc call and enabled for non-streaming. However, it's not clear how this would be accomplished since the grpc spec does not distinguish between streaming and non-streaming rpc calls at the http2 level. 

This behavior was observed using a streaming go grpc client as well as an iOS grpc client, using release `1.3.0`.

**Comment by mattklein123** [comment] 2017-06-06 20:42
This is by design. The buffer filter doesn't know anything about gRPC and just buffers the entire request. It probably should not be used in streaming API scenarios. About the only thing I can think of would be to have some type of header that shuts off the buffer.

**Comment by mattklein123** [comment] 2017-06-08 16:22
I'm going to go ahead and close this out.

**Closed by mattklein123** 2017-06-08 16:22 UTC
Labels: question

**Comment by negator** [comment] 2017-06-13 20:36
Ok thanks @mattklein123, thats what I assumed initially. Perhaps a small note in the docs would suffice for now.
