### ISSUE TITLE
dynamic cluster manager alteration at runtime

### ISSUE THREAD

**Issue by mattklein123** [lyft/envoy#144] opened 2016-10-12 17:08 UTC
1) Create polling API (like SDS API) which talk to "cluster config service"
2) Allow clusters to be added/removed at runtime

**Comment by kyessenov** [comment] 2016-10-14 18:45
Hi, we would really like to have 2). 
We have identified one compelling use-case that is hard to achieve with the static clusters.
For the OpenID discovery mechanism, the pubkey server is unknown at the configuration time. It's URL has to be fetched from a well-known location (/.well-known/openid-configuration). So we have to wait for the fetches to complete before the proxy can start, and additionally, restart the proxy to re-fetch the keys.

**Comment by mattklein123** [comment] 2016-10-14 22:41
@kyessenov can you provide a little more detail on your specific use case? How would you want the proxy to handle this exactly?

**Comment by kyessenov** [comment] 2016-10-14 23:16
In our prototype, we provide authentication functionality using JWT tokens and OpenID providers. We insert a decoder filter that looks at the header and checks that the issuer is white-listed, fetches and caches the pub-key using the discovery URL, and verifies the signature. It seems that all we need is to declare all URLs for the providers statically in the config file as upstream clusters, but the fetches can be done asynchronously after start-up. So this might not be as important to us as I originally thought.

**Comment by mattklein123** [comment] 2016-10-14 23:26
@kyessenov yeah, as long as you know all of the upstream clusters ahead of time, you should be fine (you can then use AsyncClient or a gRPC channel to call out). This issue is targeting folks that need to add new clusters at runtime and don't want to hot restart (this use case is more rare IMO, but if people create/remove clusters at runtime frequently for whatever reason they need this)

**Comment by kuroneko25** [comment] 2016-10-17 01:19
Kind of related question:
Does Envoy detect config changes and automatically hot-restart itself to load the new configuration? We have a set up where we run Envoy as the front-proxy in a Kubernetes cluster. We are loading the config using a config volume in Kubernetes and it has the ability to automatically push changes to the container without having to restart it. Does Envoy have the capability to detect changes in the config file and perform a hot-restart by itself?

**Comment by mattklein123** [comment] 2016-10-17 04:59
@kuroneko25 right now Envoy does not do any file watching and auto restart. If that is something that would be interesting feel free to open a new issue for that. The reason we don't do anything like that is this kind of stuff tends to be pretty deployment specific and in general it seems best left to the deployment infra. cc @louiscryan

**Comment by lizan** [comment] 2016-10-24 23:20
@mattklein123 @kyessenov There is actually one more step for OpenID discovery, the well-known location (/.well-known/openid-configuration) only provides the **URL** of public keys. So even we know all whitelisted JWT issuers, we don't know the URL of public keys unless you fetches all the well-know locations during the configuration. Also the URL of public keys could be changed (not expected to happen often, but possible). So either 2) or making AsyncHttpClient able to talk to any HTTP(S) server would be ideal.

**Comment by mattklein123** [comment] 2016-10-25 01:04
@lizan @kyessenov making AsyncHttpClient talk to any server is something we probably don't want to do unless you are OK with inline DNS resolution (which you probably don't want).

Can you potentially give a more complete picture of your use case for dynamic cluster update? A full flow would be useful. I don't yet think I have a complete enough picture to recommend a particular design.

**Comment by lizan** [comment] 2016-10-25 04:38
The example flow to validate a JWT with OpenID discovery:

In configuration:
- A whitelist of JWT issuers (e.g. "https://accounts.google.com")

For each request
1. The proxy receives request with "Authorization" header with JWT (in case you're not familiar with JWT, just think it is a base64 encoded JSON + signature)
2. Extract issuer from the JWT, check if it is in whitelist.
3. If the issuer is allowed, fetch OpenID configuration from well-known location (e.g. https://accounts.google.com/.well-known/openid-configuration )
4. Fetch the public keys from the URL specified in the configuration fetched in 3. (the JSON entry "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs")
5. Use the public keys fetched in 4. to verify the JWT signature.
6. If the signature is valid, then the request passed to upstream, otherwise it will be rejected.

Of course 3. and 4. can be cached for certain time. The problem is that we don't know the URL in 4. during the configuration, and it could be changed any time (not expected happening often).

**Comment by mattklein123** [comment] 2016-10-25 21:58
@lizan ok thanks very helpful. Potentially blocking the request flow for all of these fetches seems suboptimal but I guess with caching it's OK. I guess what is the optimal flow for you:

1) Just make AsyncClient work in a mode where you do blocking DNS and an arbitrary URL.
2) Be able to actually add clusters to the cluster manager at runtime (doing this as part of the request flow safely would be difficult).

It seems like for this use case you actually want 1?

**Comment by mattklein123** [comment] 2016-12-14 19:30
We are going to go ahead and implement dynamic cluster discovery via a "CDS" API. I will propose the API in the next couple of days for review.

**Comment by timperrett** [comment] 2016-12-14 20:08
Thanks Matt, this is perfect timing for us.

**Comment by rshriram** [comment] 2016-12-14 20:25
@mattklein123 just to confirm, are you doing (1) or (2) as per your comment on Oct 25th ?
(1) is similar to some form of SRV lookup for the host name? or resolving to a single IP?

```nginx
upstream backends {
    server backends.example.com:8080;
}

server {
    location / {
        proxy_pass http://backends;
    }
}
```

(2) would be similar to 
```nginx
$backends = ["backend_v1", "backend_v2", ..] #cluster names
server {
    location / {
        proxy_pass http://$backends;
    }
}
```

I am guessing you mean (1)

**Comment by mattklein123** [comment] 2016-12-14 20:50
I mean (1), but what I actually mean is an API that would return a list of clusters in exactly the same format as they are currently statically configured. So for example, the API can return an "SDS" cluster type which would then poll SDS just like any other SDS cluster. Thus, CDS/SDS can work hand in hand. It will be more clear what I am proposing when I do an API draft. I think it should be pretty clean and nice but look forward to feedback. Let's just hold the discussion until I have a proposal if possible.

**Comment by timperrett** [comment] 2016-12-14 22:12
@mattklein123 Having a CDS API would be great. That would service exactly what we need to use Envoy (we already implemented SDS protocol with our own backend). Cheers

**Comment by mattklein123** [comment] 2016-12-14 23:37
Here is what I am thinking for the API:

```json
GET /v1/clusters/(string: service_cluster)/(string: service_node)
```

**Where:**

``service_cluster``: Comes from [here](https://lyft.github.io/envoy/docs/operations/cli.html#cmdoption-service-cluster). Allows returning clusters based on the caller, if desired. Can be set to set to global value if implementation does not care.
``service_node``: Comes from [here](https://lyft.github.io/envoy/docs/operations/cli.html#cmdoption-service-node). Allows returning clusters based on the caller, if desired. Can be set to set to global value if implementation does not care.

**Returns:**

```json
{
  "clusters": []
}
```

Where each cluster in the ``clusters`` array is a cluster definition exactly as defined [here](https://lyft.github.io/envoy/docs/configuration/cluster_manager/cluster.html).

**Implementation notes:**

Envoy will poll the CDS endpoint at some interval. All returned clusters will be installed dynamically into the running server. Clusters that are no longer present will be gracefully removed. This will be usable alongside static cluster definitions.

For dynamic clusters, Envoy will hash the configuration JSON so that it knows if a cluster configuration has changed (for example a static host IP has changed, DNS has changed, etc.) so that it can be more efficient about only reloading when necessary.

**Comment by mattklein123** [comment] 2016-12-14 23:39
@timperrett @jhspaybar @kyessenov @lizan let me know how this looks. This is not that hard to implement so I will do it relatively soon once we agree on the API and the semantics.

**Comment by jhspaybar** [comment] 2016-12-15 00:26
This seems reasonable.  It seems as well that if I wanted to avoid additional calls to the SDS I could have the CDS return a static set of hosts in the cluster definition?  If our internal systems then were completely using the CDS approach I wouldn't need to bother writing the SDS?

**Comment by mattklein123** [comment] 2016-12-15 00:36
@jhspaybar yup if you want to just send down all static clusters that would work fine. Then you can avoid SDS entirely.

**Comment by mattklein123** [comment] 2016-12-15 00:38
@jhspaybar though, I just realized, that if you want to use some of the more advanced components such as zone aware load balancing, you probably need to use SDS, or we need to also make the static configuration more complicated. We can cross that bridge when we come to it.

**Comment by jhspaybar** [comment] 2016-12-15 06:04
Ah, that makes sense.  Lets keep it simple for now.

**Comment by timperrett** [comment] 2016-12-15 17:59
@mattklein123 this looks good to me, although I did have a couple of questions:

1. Semantically, what's the difference between `service_name` and `service_node`. I imagine the former to be a logical name (or cluster name), e.g. "accounts-1.0" or something, whilst the latter might be the node name, or IP address?

2. When the config reloads internally to Envoy, will there be any downtime or similar? Just trying to understand how this would affect the operational runtime. 

Thanks!

**Comment by mattklein123** [comment] 2016-12-15 18:19
@timperrett 

1) The semantics are up to the deployment, but how we use it is exactly as you speculated. service_cluster would be something like "accounts" or "eta" whereas service_node is something like an EC2 instance ID, container ID, IP/port pair, etc.

2) Yes, it will be zero downtime*

* It's a little tricky if there is an expectation that a cluster with the same name gets swapped in which has a different resolution target (e.g., different DNS, different SDS target, different health checking, etc.). A naive implementation would swap it in, but then there would be a short delay in which the cluster wouldn't actually have any resolved/health checked members. A more robust implementation would pre-initialize the new cluster (single SDS/DNS pass, single HC pass) before swapping it in. We will end up doing the latter but probably as an iterative change.

**Comment by timperrett** [comment] 2016-12-15 18:37
@mattklein123 thanks for the info. That sounds fine to me. In our case, all the clusters are uniquely named, so that name shadowing would not happen for us, and given we're already doing SDS to turn cluster names into IPs, we should be golden :-D

**Comment by timperrett** [comment] 2016-12-29 19:38
@mattklein123 Happy Holidays! Just to plan accordingly, what's the rough ETA for this work? I was going to work on implementing the proposed protocol this week in our glue API the Envoy talks to, such that we're ready to go with it as soon as its merged into Envoy, but just trying to get an idea if thats overly optimistic, or if we need to plan for something else in the mean time?

**Comment by mattklein123** [comment] 2016-12-29 23:49
@timperrett I took a detour into redis but I plan on doing this next week. 

Question: How are you going to select the dynamic cluster? Do you need https://github.com/lyft/envoy/issues/308 also? Since currently the route table is static I assume you also need some way of selecting the cluster via header or something along those lines? Or do you also really need https://github.com/lyft/envoy/issues/298 for a complete solution

**Comment by timperrett** [comment] 2016-12-31 19:54
@mattklein123 Thanks for the reply and sorry for my delay (christmas etc); back to work full time from Monday. 

We would want #308 to satisfy all our use cases (I can email you a document with the cases we need to satisfy if that helps), but now having seen #298, man, #298 would really help us avoid reloading envoy. As I see it #308 is satisfying a discrete use-case from #298, so yeah, for a complete solution we'd need both.

This is so awesome @mattklein123 and im stoked on getting this up and running! I'm implementing the CDS API in our integration layer at the moment :-)

**Comment by mattklein123** [comment] 2016-12-31 20:01
@timperrett if you could email me that doc that would be great. I suspect @rshriram would also be interested if you don't mind being public about it. https://github.com/lyft/envoy/issues/298 is not hard to implement so I will probably just do that also. So I guess give me about 2 weeks to get it all done.

**Comment by amb67** [comment] 2017-01-17 15:34
@mattklein123 It would be useful for CDS to return not only list of clusters but weights associated with each cluster. The use case for this is global load balancing where Envoy would be able to split traffic between the clusters for the same service. While this may not be that important when using Envoy in a sidecar configuration, it is super important if Envoy is used as a proxy in the middle.

**Comment by mattklein123** [comment] 2017-01-17 18:51
@amb67 it is by design that clusters/cluster manager do not participate in routing (including weighting). Weighted routing is accomplished via the routing engine. There are a few upcoming changes that will make it easier to perform dynamic weighting updates beyond the runtime system we provide today:
1) We will add RDS API to go along with SDS and CDS API: https://github.com/lyft/envoy/issues/298
2) We will add an easier to use multi-cluster weighted routing rule: https://github.com/lyft/envoy/issues/247

Both of these should land in the next 2 weeks or so: cc @rshriram

**Comment by amb67** [comment] 2017-01-18 04:10
So the workflow will be the following steps?
1. Call CDS to get list of clusters
2. For each cluster, get list of IPs in this cluster via SDS
3. Call RDS and as part of it get cluster weight overrides.


In our case cluster weights always be dynamic, and they change very often
so we would need a stream. Short of stream, we would need to get weights
continuously through the API.

Also, with these APIs, one more API is missing - load reporting API. i.e.
Envoy reports all per cluster metrics (number of requests, number of
errors, custom metrics) over some interval, let's say 1 second.  In return
it gets dynamic weights.

**Comment by mattklein123** [comment] 2017-01-18 17:01
@amb67 For better or worse, we are trying to build a system where customers with vastly different needs can come and use the complexity that they require, and no more. This ranges from some customers that want a completely static config, to your requirements which are probably the most complicated that we have considered so far.

I need to get this better documented in the official docs once CDS and RDS are implemented, but here is the rough lay of the land in terms of what is currently possible (overall I am quite happy with the direction we have gone. I think it's quite flexible and users only have to consume the complexity they absolutely require):

- Dynamic clusters (not cluster members) can be fetched with the CDS API. These are just cluster definitions and don't deal with routing.
- With either dynamic or static clusters, dynamic *members* can be fetched either with DNS or SDS. Note that if you are using CDS, you don't necessarily need to use SDS, you could just return static clusters with fixed sets of IP/ports and not use SDS. The reason we will continue to have both is that for some customers the system that provides CDS is not the same system that provides SDS (in your case it might be the same system).
- Routes can either be configured statically or fully dynamically with RDS.
- Within a route table, it's possible to do "runtime" switching and weighting via the "runtime" system.  See [here](https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/route.html#runtime) and [here](https://lyft.github.io/envoy/docs/configuration/http_conn_man/route_config/traffic_shifting.html). Currently, the runtime system reads from an atomic set of FS files since many companies use a system like this to distribute "runtime" configuration. We have also discussed adding an API for fetching runtime data. See https://github.com/lyft/envoy/issues/272.
- With RDS, it will be possible to not bother with runtime, since you will be able to change the entire route table as you wish. We will however keep the runtime system, because some people don't want the complexity of implementing the full RDS API.

So now to get to your explicit questions:
- Fast updates: In addition to the REST RDS/CDS APIs, I would propose that we also define gRPC streaming APIs that provide the same information. Instead of REST polling, Envoy would just set up a persistent streaming response for RDS/CDS and the updates would be applied "instantly." I would prefer to keep the REST versions, because for many customers it's much simpler to implement. We can support both easily.
- Load reporting: I think there are a few options here. 1) You take the existing statsd output from Envoy (which includes copious stats) and use that as input to your algorithms. 2) We define a new "stat sink" which actually writes to an API, so that you get periodic flushes of all Envoy stats in API format without you having to do statsd/api conversion yourself. 3) We define an entirely new API (probably gRPC streaming) which gets pushed specific data for each cluster that we pre-define. All of these are relatively straightforward IMO. The data is easy, as Envoy already has it all and spits it out to statsd.

**Comment by amb67** [comment] 2017-01-18 17:42
@mattklein123 Thank you for detailed explanation. Given that our requirements are so dynamic and tilt Envoy APIs to more complex, I am happy to help you to design them.

**Comment by mattklein123** [comment] 2017-01-19 01:03
For those following along, I talked to @amb67 offline. We will circle back in a couple of weeks with a more concrete public proposal for any new (likely gRPC) APIs. In the near term, I am continuing forward with the existing REST CDS/RDS proposals to satisfy all the other known use cases.

**Closed** 2017-01-20 20:22 UTC
Labels: enhancement
