### ISSUE TITLE
Route to unknown hosts

### ISSUE THREAD

**Issue by jhspaybar** [lyft/envoy#283] opened 2016-12-11 00:53 UTC
I've gone through most of the docs, and it looks like in order to route somewhere I need an upstream defined.  The use case I'm trying to see if it's possible is to set a header like a host header and have the value in the header be sent to an SDS to resolve targets.  Maybe this could be considered a dynamic upstream?  Based on what I'm reading in the documentation it seems like when using the host header it needs to be resolved from a set of static things I've already defined.

**Comment by mattklein123** [comment] 2016-12-11 01:38
As currently implemented, it's true that the HTTP router must match a pre-defined cluster. This is by design in the sense that in most cases users do not want to block the forwarding path on host resolution (whether to SDS, DNS resolution, etc.).

With that said, there have been multiple requests for some variant of this feature. See https://github.com/lyft/envoy/issues/144 for a similar request.

If possible can you provide more information on your use case? Do you actually want to block every request on an external route fetch? Is this for development where you don't care about performance? If there was an additional SDS like API that could asynchronously fetch and dynamically instantiate cluster definitions would that work (call it the CDS, "cluster discovery service")?

**Comment by jhspaybar** [comment] 2016-12-14 18:29
Sorry it took me so long to get back to answer your question here.  So, I think the other issue is helpful in that I would expect configurations for new services to be maintained by the service owner, but then be pushed to all clients dynamically and was something I was going to be looking for next.

Having that probably also solves my specific use case here in that it is a reasonable workflow for someone to add their custom target cluster dynamically, have it propagate to all clients, and only then use that new target.  I'm also okay with a synchronous higher latency lookup, though with the "CDS" it might not be required.

**Comment by mattklein123** [comment] 2016-12-14 19:17
If CDS would work for your use case, I would rather go ahead and implement that first. In some ways it's simpler than synchronous resolution and is more inline with requests that we have gotten from other users.

The final question would be related to how the route table would work. I assume you would want a generic route table that just selects the cluster to use based on an HTTP header (either :authority or something else)? In such a deployment, the route table could be static and would not need to be dynamically updated.

**Comment by jhspaybar** [comment] 2016-12-14 19:20
Yes, if I could dynamically update clusters, I'd expect to be able to read a header like :authority and have the value be a cluster name in the dynamic set.

**Comment by mattklein123** [comment] 2016-12-14 19:21
OK, that sounds good to me. I will do a proposal for the CDS API in the next few days. There are multiple people interested in this.

**Comment by mattklein123** [comment] 2016-12-14 19:29
I'm going to close this in favor of https://github.com/lyft/envoy/issues/144

I will put the CDS API proposal there and use that issue to track implementation.

**Closed by mattklein123** 2016-12-14 19:29 UTC
Labels: duplicate

**Comment by jhspaybar** [comment] 2016-12-24 04:19
@mattklein123 sorry to reply to a closed issue, but after some extra testing, I think I need to be able to read a header that isn't the ":authority" header.  My experimentation with grpc-java at least seems to require ":authority" to be localhost or 127.0.0.1 so that I can talk to the client side of my envoy mesh and then specify something like "upstream=foo" to match the actual cluster I'm targeting.  I'll continue to follow the other thread from here.

**Comment by jhspaybar** [comment] 2016-12-24 15:39
I take it back, it appears I missed a ChannelOption which allows me to override the Channel authority for a single call, so I could install an interceptor that just adds this to every call.

**Comment by mattklein123** [comment] 2016-12-24 16:29
@jhspaybar I opened https://github.com/lyft/envoy/issues/308 to track adding the ability to specify the cluster in a header. This is slightly orthogonal to the CDS stuff so we can track in a different issue. When implemented we will allow specifying an arbitrary header of your choice.
