### ISSUE TITLE
Spoting memory leak on ubuntu 14.04

### ISSUE THREAD

**Issue by fabware** [lyft/envoy#137] opened 2016-10-11 01:16 UTC
Compiled an envoy binary statically on a dev machine(ubuntu 14.04), and deployed it on a cloud virtual machine(ubuntu 14.04).

Spot steady cpu and memory increase until the host is unresponsive. Blue line in the below image represent CPU usage. 

We have very low traffic so restart it daily is not a big deal. Just report it, and we are currently migrated to a aws host of ubuntu 16.04, will monitor it further.

![image](https://cloud.githubusercontent.com/assets/160636/19255527/8062988a-8f91-11e6-8ae4-ce8751d85ad1.png)

**Comment by mattklein123** [comment] 2016-10-11 15:15
Can you potentially provide more info showing that Envoy is the issue? For example 'ps aux | grep envoy', 'top', 'perf top', 'perf record', etc. 

Assuming Envoy is the cause of the runaway CPU we won't be able to help debug without more information.

**Comment by fabware** [comment] 2016-10-12 04:04
Thanks for your reply, sure I'll gather more info if we get this problem on the new machine. 

I'm sure envoy hog up all cpu and cause problem, though I didn't note numbers at that time.

**Comment by mattklein123** [comment] 2016-10-21 02:35
Going to close this out. Please reopen if you have more info and we are happy to help debug.

**Closed by mattklein123** 2016-10-21 02:35 UTC
Labels: question
